apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx-acme
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: webapprouting.kubernetes.azure.com/nginx

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt-prod@adonm.fastmail.fm
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx-acme
